### ISSUE TITLE
I can't install civix-qt

### ISSUE THREAD

**Issue by mati3** [exofoundation/CivX-Qt#14]
Error: libdb_cxx-4.8.so: cannot open shared object file: no such file or directory.

I use a machine ubuntu-18-04. 
I have install all the require library.

**Comment by erseco** [comment]
@kentlangley and @checho1989 check the PR #15 from @mati3 and if you can please add a release for Ubuntu 18.04 LTS

Thanks!

**Comment by mati3** [comment]
I solved this issue with the last actualization on PR of the following link: https://github.com/exofoundation/CivX-Qt/pull/15

**Comment by turcol** [comment]
@mati3 you can download the latest binaries for Linux without need to build it. Look here for additional information:
https://github.com/exoeconomy/EXOS-Qt/issues/17#issuecomment-487449021
